import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // 快速开始
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'doc',
        id: 'guide/installation',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'guide',
        },
      ],
    },
    // 产品特性
    {
      type: 'category',
      label: 'Product Features',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'doc',
        id: 'product-features/strict-mode',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'product-features',
        },
      ],
    },
    // 私有化部署
    {
      type: 'category',
      label: 'Local deployment',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'doc',
        id: 'deployment/introduction',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'deployment',
        },
      ],
    },
    // 最佳实践
    {
      type: 'category',
      label: 'Best Practices',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'doc',
        id: 'best-practices/best-practices1',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'best-practices',
        },
      ],
    },
    // 常见问题
    'FAQ',
    // 视频教程
    'tutorial-videos/video',
    // 套餐&计费说明
    {
      type: 'category',
      label: 'Billing',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'doc',
        id: 'billing/usage',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'billing',
        },
      ],
    },
    // 版本更新
    {
      type: 'category',
      label: 'Version notes',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'doc',
        id: 'version-notes/version_notes',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'version-notes',
        },
      ],
    },
    // 其他
    {
      type: 'category',
      label: 'Policy',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'doc',
        id: 'policy/privacy-policy',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'policy',
        },
      ],
    },
  ],
};

export default sidebars;
