import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebarsCli: SidebarsConfig = {
  cliSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: true,
      collapsed: true,
      items: [
        'guide/introduction',
        'guide/installation',
        'guide/quick_start',
        'guide/feature',
        'guide/cli',
        'guide/ide',
      ],
    },
    {
      type: 'category',
      label: 'Configuration',
      collapsible: true,
      collapsed: true,
      items: [
        'config/plugins',
        'config/formatters',
        'config/config',
        'config/keybinds',
        'config/modes',
        'config/models',
        'config/tools',
        'config/settings',
        'config/notify',
        'config/network',
        'config/themes',
        'config/custom-agent',
        'config/slash-command',
        'config/provider',
        'config/rules',
        'config/custom-tools',
        'config/acp',
        'config/lsp',
        'config/mcp',
        'config/skills',
      ],
    },
    {
      type: 'category',
      label: 'Product Characteristics',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'product-characteristics',
        },
      ],
    },
    'best-practices',
    'FAQ',
    'redirect',
  ],
};

export default sidebarsCli;
